# Generated by Django 4.2.10 on 2024-08-16 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_amount_balance_user_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribed_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки'),
        ),
    ]
