# Generated by Django 4.2.10 on 2024-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название группы'),
            preserve_default=False,
        ),
    ]
