# Generated by Django 4.2.10 on 2024-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для покупки'),
        ),
    ]
